### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by dotps1** [ChaseFlorell/psDoc#5] opened 2016-04-12 17:23 UTC
when I run .\psDoc.ps1 -ModuleName MyModule I get an error:

```
out-file : Could not find a part of the path 'C:\Users\me\Downloads\psDoc-master\psDoc-master\src\help\index.html'.
At C:\Users\me\Downloads\psDoc-master\psDoc-master\src\psDoc.ps1:54 char:1
+ Invoke-Expression $template > "$outputDir\$fileName"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```

bummer

**Comment by ChaseFlorell** [comment] 2016-04-12 17:32
Dupe of #4

**Closed as completed by ChaseFlorell** 2016-04-12 17:32 UTC
